import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "G5qRYKkRnWQ",
    video_title: "Bigger Penis Is Better? सच जानें",
    video_description: `Bigger is better — female body anatomy कुछ और कहती है
Hard Facts with Kundan Bhoot`,
    tags: ["Raaz MD", "PenisSize", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "G5qRYKkRnWQ",
    publish_date: "2026-04-07",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/G5qRYKkRnWQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:51",
    software_used: ["CapCut"],
  },
  {
    id: "CRxEa40onZ8",
    video_title: "Size छोटा है? Doctor बोले — पहले ये Check करो",
    video_description: "Small Penis Anxiety — ज़्यादातर cases में size normal होता है, problem कहीं और है",
    tags: ["PenisSize", "MensHealth", "NoShameClinic", "Shorts"],
    cover_image: "CRxEa40onZ8",
    publish_date: "2026-04-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/CRxEa40onZ8",
    project_images: [],
    category: ["Shorts"],
    duration: "0:57",
    software_used: ["CapCut"],
  },
  {
    id: "H9N5jvbmNhI",
    video_title: "Penis Size की सच्चाई — Doctor ने सब बता दिया",
    video_description: "500+ consultations में सबसे ज़्यादा पूछा जाने वाला सवाल — size normal है क्या?",
    tags: ["PenisSize", "MensHealth", "NoShameClinic", "Shorts"],
    cover_image: "H9N5jvbmNhI",
    publish_date: "2026-04-02",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/H9N5jvbmNhI",
    project_images: [],
    category: ["Shorts"],
    duration: "0:39",
    software_used: ["CapCut"],
  },
  {
    id: "5maln15Dfrk",
    video_title: "टेढ़ा Penis से Partner Unhappy? Doctor बोले...",
    video_description: `Curved penis और partner satisfaction — Dr. Samarth Kaul का clinical experience
No Shame Clinic | Raaz MD`,
    tags: ["PenisSize", "MensHealth", "NoShameClinic", "Shorts"],
    cover_image: "5maln15Dfrk",
    publish_date: "2026-04-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/5maln15Dfrk",
    project_images: [],
    category: ["Shorts"],
    duration: "0:36",
    software_used: ["CapCut"],
  },
];
