import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "QgXnAqiuBsA",
    video_title: "Option 03 (Hook-focused & High Click-Through): 32 Year Old Businessman Shared His Timing Journey 🤫",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "QgXnAqiuBsA",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/QgXnAqiuBsA",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:28",
    software_used: ["CapCut"],
  },
  {
    id: "OpByRsA3lbA",
    video_title: "Option 02 (Hook-focused & High Click-Through) : WhatsApp पर एक 'Hi' भेजा और बदल गई Married Life! 📈",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "OpByRsA3lbA",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/OpByRsA3lbA",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "Myb3O9M9Ud8",
    video_title: "Option 1 (Hook-focused & High Click-Through): WhatsApp के एक 'Hi' ने कैसे बचाया इनका रिश्ता? 🚀",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "Myb3O9M9Ud8",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Myb3O9M9Ud8",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "CqJeLRk_6Eg",
    video_title: "Don't Let Intimacy Issues Ruin Your Relationship! 🛑 | Take The 2-Minute Men's Test",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "CqJeLRk_6Eg",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/CqJeLRk_6Eg",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:34",
    software_used: ["CapCut"],
  },
  {
    id: "BOrbtlQoCAI",
    video_title: "45 Days में 90% Recovery! 🌟 | Raaz App से मिला परमानेंट आराम",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "BOrbtlQoCAI",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/BOrbtlQoCAI",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:56",
    software_used: ["CapCut"],
  },
  {
    id: "eHye0PyxNkQ",
    video_title: "सिर्फ 10 Days में दिखने लगा असर! 📈 | Best Timing Solution For Men",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "eHye0PyxNkQ",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/eHye0PyxNkQ",
    project_images: [],
    category: ["Meta Ads"],
    duration: "1:05",
    software_used: ["CapCut"],
  },
  {
    id: "l9lKaV2T1vQ",
    video_title: "0 से 5 Minute तक कैसे बढ़ी Timing? ⏱️ | Live Proof & Result!Video",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "l9lKaV2T1vQ",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/l9lKaV2T1vQ",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:54",
    software_used: ["CapCut"],
  },
  {
    id: "MMHKvEl1Foo",
    video_title: "Option 10 (Hook-focused & High Click-Through): Bedroom Moments में दिक्कत? |",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "MMHKvEl1Foo",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/MMHKvEl1Foo",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "1PqnvNM08pU",
    video_title: "Option 09 (Hook-focused & High Click-Through): Inki Wife को समझ आ गया था कि इलाज जरूरी है! 👍",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "1PqnvNM08pU",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/1PqnvNM08pU",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "ycsDGATJKaU",
    video_title: "Option 08 (Hook-focused & High Click-Through): क्या बेडरूम प्रॉब्लम्स से आपके रिश्ते टूट रहे हैं? 😟",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "ycsDGATJKaU",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/ycsDGATJKaU",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:26",
    software_used: ["CapCut"],
  },
  {
    id: "mxD5sNhhF30",
    video_title: "Option 07 (Hook-focused & High Click-Through): Early Finish की समस्या का परमानेंट और सही इलाज! ❌",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "mxD5sNhhF30",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/mxD5sNhhF30",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:27",
    software_used: ["CapCut"],
  },
  {
    id: "qZtOwEOOVKM",
    video_title: "Curved Penis से Confidence टूट रहा है? ये सुनो",
    video_description: "A look into how stressing over curvature causes performance anxiety, low confidence, and mental health strain.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "qZtOwEOOVKM",
    publish_date: "2026-04-21",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/qZtOwEOOVKM",
    project_images: [],
    category: ["Featured", "Shorts"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "CRxEa40onZ8",
    video_title: "Size छोटा है? Doctor बोले — पहले ये Check करो",
    video_description: "Breaking down \"small penis anxiety\" and explaining how weight gain and grooming directly alter visual perception.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "CRxEa40onZ8",
    publish_date: "2026-04-04",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/CRxEa40onZ8",
    project_images: [],
    category: ["Featured", "Shorts"],
    duration: "0:57",
    software_used: ["CapCut"],
  },
  {
    id: "KIi-GNrS3Wo",
    video_title: "Indian मर्दों का Size छोटा होता है?",
    video_description: "Deep-diving into decades of medical data analyzing why perceptions around the physical attributes of Indian men are flawed.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "KIi-GNrS3Wo",
    publish_date: "2026-04-04",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/KIi-GNrS3Wo",
    project_images: [],
    category: ["Featured", "Shorts"],
    duration: "0:35",
    software_used: ["CapCut"],
  },
  {
    id: "9FybW5O9YlY",
    video_title: "Normal Penis Size कितना है? 100 में से 90 मर्द...",
    video_description: "Presenting the anatomical bell curve showing where the vast majority of men place regarding measurement metrics.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "9FybW5O9YlY",
    publish_date: "2026-04-05",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/9FybW5O9YlY",
    project_images: [],
    category: ["Featured", "Shorts"],
    duration: "0:39",
    software_used: ["CapCut"],
  },
  {
    id: "-kY5Sb3gSHE",
    video_title: "Option 06 (Hook-focused & High Click-Through): Timing की दिक्कत ने शादीशुदा जिंदगी में डाली दरार? 💔",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "-kY5Sb3gSHE",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/-kY5Sb3gSHE",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "s0vDWGJYG84",
    video_title: "Option 05 (Hook-focused & High Click-Through): चिड़चिड़ापन से लेकर 8 मिनट की टाइमिंग तक का सफर! 📉",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "s0vDWGJYG84",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/s0vDWGJYG84",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:30",
    software_used: ["CapCut"],
  },
  {
    id: "Wnzl6GDhkfE",
    video_title: "Option 04 (Hook-focused & High Click-Through): बेडरूम की दिक्कतों को रिश्ते पर हावी मत होने दें! 🛑",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "Wnzl6GDhkfE",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Wnzl6GDhkfE",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "T6kb4AUGGqg",
    video_title: "उम्र के साथ Morning Erections कम क्यों होते हैं? | Science Explained",
    video_description: "A scientific overview of how nocturnal penile tumescence (morning erections) naturally decreases in frequency and intensity with age, as observed in sleep studies.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "T6kb4AUGGqg",
    publish_date: "2026-05-07",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/T6kb4AUGGqg",
    project_images: [],
    category: ["Shorts"],
    duration: "0:35",
    software_used: ["CapCut"],
  },
  {
    id: "BsHrg9OSpgQ",
    video_title: "Morning Erection: 90 Min रोज़ रात- क्यों?",
    video_description: "An explanation of nocturnal erections acting as vital oxygen therapy for penile tissues, boosting oxygen levels to maintain tissue health and elasticity.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "BsHrg9OSpgQ",
    publish_date: "2026-05-05",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/BsHrg9OSpgQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:33",
    software_used: ["CapCut"],
  },
  {
    id: "WPpFZ5OMINQ",
    video_title: "हर रात 4 Erections | Science क्या कहती है?",
    video_description: "Insights into how morning erections function across all ages sync with REM sleep cycles without requiring sexual thoughts.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "WPpFZ5OMINQ",
    publish_date: "2026-05-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/WPpFZ5OMINQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:37",
    software_used: ["CapCut"],
  },
  {
    id: "5maln15Dfrk",
    video_title: "टेढ़ा Penis से Partner Unhappy? Doctor बोले...",
    video_description: "Addressing misconceptions regarding penile curvature, explaining that it rarely affects intimacy and debunking online pills or correction devices.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "5maln15Dfrk",
    publish_date: "2026-04-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/5maln15Dfrk",
    project_images: [],
    category: ["Featured", "Shorts"],
    duration: "0:36",
    software_used: ["CapCut"],
  },
  {
    id: "977u2dwYd_0",
    video_title: "Penis पहले Straight था, अब Tedha — Serious है?",
    video_description: "Clinical clarity on whether a shift or curvature in shape over time is serious, highlighting what symptoms require medical attention.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "977u2dwYd_0",
    publish_date: "2026-04-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/977u2dwYd_0",
    project_images: [],
    category: ["Shorts"],
    duration: "0:22",
    software_used: ["CapCut"],
  },
  {
    id: "xNDfUooyCqw",
    video_title: "Peyronie's Disease क्या है? — डरो मत, समझो",
    video_description: "An explanation of Peyronie's disease, how internal plaque/scar tissue causes bending during an erection, and who it commonly affects.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "xNDfUooyCqw",
    publish_date: "2026-04-23",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/xNDfUooyCqw",
    project_images: [],
    category: ["Shorts"],
    duration: "0:38",
    software_used: ["CapCut"],
  },
  {
    id: "H9N5jvbmNhI",
    video_title: "Penis Size की सच्चाई — Doctor ने सब बता दिया",
    video_description: "Medical facts concerning the average erect length for Indian men, matching it closely against global metrics to clear up internet-born myths.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "H9N5jvbmNhI",
    publish_date: "2026-04-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/H9N5jvbmNhI",
    project_images: [],
    category: ["Shorts"],
    duration: "0:39",
    software_used: ["CapCut"],
  },
  {
    id: "eUR0CIZ2ow0",
    video_title: "Size छोटा लग रहा है? असली Problem ये हो सकती है",
    video_description: "Explaining a massive study revealing that anxiety about size often misidentifies an underlying issue with erection firmness or quality.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "eUR0CIZ2ow0",
    publish_date: "2026-04-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/eUR0CIZ2ow0",
    project_images: [],
    category: ["Shorts"],
    duration: "0:43",
    software_used: ["CapCut"],
  },
  {
    id: "R9QeTSN-nO8",
    video_title: "Oil से Size बढ़ेगा? Doctor का सीधा जवाब",
    video_description: "Differentiating medical reality from promotional claims, explaining that creams or oils only briefly increase surface blood flow but cannot expand physical tissue.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "R9QeTSN-nO8",
    publish_date: "2026-04-05",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/R9QeTSN-nO8",
    project_images: [],
    category: ["Shorts"],
    duration: "0:46",
    software_used: ["CapCut"],
  },
  {
    id: "fgqYbtZpkBY",
    video_title: "Size बढ़ाने वाले Products? सब SCAM है — Doctor Explains",
    video_description: "Exposing tissue expansion product scams and directing focus toward treating actual erectile dysfunction effectively.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "fgqYbtZpkBY",
    publish_date: "2026-04-06",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/fgqYbtZpkBY",
    project_images: [],
    category: ["Shorts"],
    duration: "0:43",
    software_used: ["CapCut"],
  },
  {
    id: "G5qRYKkRnWQ",
    video_title: "Bigger Penis Is Better? सच जानें",
    video_description: "Explaining anatomical sensitivity facts regarding female pleasure zones and detailing the nerve endings responsible for stimulation.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "G5qRYKkRnWQ",
    publish_date: "2026-04-07",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/G5qRYKkRnWQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:51",
    software_used: ["CapCut"],
  },
  {
    id: "mdbenYuF7pM",
    video_title: "Indian Men का Average Size — Doctor-Measured Data",
    video_description: "Real clinical experiences breaking down how patients confuse performance/erection quality anxiety with sizing issues.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "mdbenYuF7pM",
    publish_date: "2026-04-08",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/mdbenYuF7pM",
    project_images: [],
    category: ["Shorts"],
    duration: "0:41",
    software_used: ["CapCut"],
  },
  {
    id: "oMBUNwPHD-w",
    video_title: "Porn vs Reality — Penis Size का सच क्या है?",
    video_description: "Dissecting how curated camera angles, lighting, and selective casting set up deeply unrealistic and harmful standard expectations.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "oMBUNwPHD-w",
    publish_date: "2026-04-09",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/oMBUNwPHD-w",
    project_images: [],
    category: ["Shorts"],
    duration: "0:45",
    software_used: ["CapCut"],
  },
  {
    id: "UMzqMhH6vQI",
    video_title: "Straight Penis कितने मर्दों का होता है? जवाब चौंकाएगा",
    video_description: "Explaining that curvatures up to 30 or 60 degrees can be completely natural and stable, without impacting physical capability.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "UMzqMhH6vQI",
    publish_date: "2026-04-18",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/UMzqMhH6vQI",
    project_images: [],
    category: ["Shorts"],
    duration: "0:28",
    software_used: ["CapCut"],
  },
  {
    id: "EwpM2r4MLWk",
    video_title: "Penis टेढ़ा दिखता है? 56% मर्द ग़लत समझते हैं",
    video_description: "Discussing how looking downward creates an unflattering perspective angle, causing more than half of men to overestimate asymmetry.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "EwpM2r4MLWk",
    publish_date: "2026-04-19",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/EwpM2r4MLWk",
    project_images: [],
    category: ["Shorts"],
    duration: "0:28",
    software_used: ["CapCut"],
  },
  {
    id: "v3tMii54Pqk",
    video_title: "Masturbation से Penis टेढ़ा होता है? सच जान लो",
    video_description: "Debunking a common physiological myth by explaining that normal habits do not cause curvature or structural alignment shifts.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "v3tMii54Pqk",
    publish_date: "2026-04-20",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/v3tMii54Pqk",
    project_images: [],
    category: ["Shorts"],
    duration: "0:35",
    software_used: ["CapCut"],
  },
  {
    id: "2sZcM85ENE8",
    video_title: "Penis टेढ़ा — कब Normal, कब Doctor ज़रूरी?",
    video_description: "A definitive guide outlining the baseline differences between natural long-term curvature and sudden shifts that demand professional care.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "2sZcM85ENE8",
    publish_date: "2026-04-20",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/2sZcM85ENE8",
    project_images: [],
    category: ["Shorts"],
    duration: "0:50",
    software_used: ["CapCut"],
  },
  {
    id: "frWKm_rsM_0",
    video_title: "English Medicines से साइड इफेक्ट का डर? 💊 | Choose Safe & Doctor Recommended Solution",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "frWKm_rsM_0",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/frWKm_rsM_0",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:39",
    software_used: ["CapCut"],
  },
  {
    id: "bKg8FvqcS9c",
    video_title: "\"लोग मज़ाक उड़ाएंगे...\" 🤫 | इस डर को छोड़ो और 4 महीनों में पाओ 100% Recovery!",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "bKg8FvqcS9c",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/bKg8FvqcS9c",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:59",
    software_used: ["CapCut"],
  },
  {
    id: "olLw5vYaL1Q",
    video_title: "2 Minute से बढ़कर सीधे Perfect Timing! ⏱️ | 100% Real User Results",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "olLw5vYaL1Q",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/olLw5vYaL1Q",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:56",
    software_used: ["CapCut"],
  },
  {
    id: "ZkdAabgfw9M",
    video_title: "बिना पैसों की चिंता किए कराएं Test! 🤝 | Raaz App आपके साथ है",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "ZkdAabgfw9M",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/ZkdAabgfw9M",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:52",
    software_used: ["CapCut"],
  },
  {
    id: "iO_fTF4ycbw",
    video_title: "2 साल पुरानी समस्या, सिर्फ 4 महीनों में 100% ठीक! 💍 | Married Life Solution",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "iO_fTF4ycbw",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/iO_fTF4ycbw",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:46",
    software_used: ["CapCut"],
  },
  {
    id: "t_cVVrXW68o",
    video_title: "Early Discharge & Erection का पक्का इलाज! 🛑 | Stop Wasting Money On Quacks",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "t_cVVrXW68o",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/t_cVVrXW68o",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:50",
    software_used: ["CapCut"],
  },
  {
    id: "n1to5tKIyz8",
    video_title: "Kegel Exercise से बढ़ाएं Performance! 🧘‍♂️ | डॉक्टर से सीखें सही तरीका",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "n1to5tKIyz8",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/n1to5tKIyz8",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:44",
    software_used: ["CapCut"],
  },
  {
    id: "lPv2C81qglk",
    video_title: "\"हारना नहीं है...\" 🛡️ | अपनी कमजोरी को दूर करने का 100-Day Plan",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "lPv2C81qglk",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/lPv2C81qglk",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:56",
    software_used: ["CapCut"],
  },
  {
    id: "bnJtlni01eY",
    video_title: "Partner को करें 100% Satisfy ❤️ | Timing बढ़ाने का असली डॉक्टर राज़",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "bnJtlni01eY",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/bnJtlni01eY",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:53",
    software_used: ["CapCut"],
  },
  {
    id: "L9-Rde64xDk",
    video_title: "Timing कम होने से पार्टनर है नाराज? 🤫 | Get 100% Secret Solution From Home",
    video_description: "",
    tags: ["Metaads"],
    cover_image: "L9-Rde64xDk",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/L9-Rde64xDk",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:58",
    software_used: ["CapCut"],
  },
  {
    id: "featured-hidden-placeholder-id",
    video_title: "Featured Category Placeholder",
    video_description: "Hidden system placeholder to ensure the website filter button continues to render safely.",
    tags: ["System"],
    cover_image: "",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["Featured"],
    duration: "0:00",
    software_used: [],
  },
];
