import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "T6kb4AUGGqg",
    video_title: "उम्र के साथ Morning Erections कम क्यों होते हैं? | Science Explained",
    video_description: "A scientific overview of how nocturnal penile tumescence (morning erections) naturally decreases in frequency and intensity with age, as observed in sleep studies.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "T6kb4AUGGqg",
    publish_date: "2026-05-07",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/T6kb4AUGGqg",
    project_images: [],
    category: ["Shorts"],
    duration: "0:35",
    software_used: ["CapCut"],
  },
  {
    id: "BsHrg9OSpgQ",
    video_title: "Morning Erection: 90 Min रोज़ रात- क्यों?",
    video_description: "An explanation of nocturnal erections acting as vital oxygen therapy for penile tissues, boosting oxygen levels to maintain tissue health and elasticity.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "BsHrg9OSpgQ",
    publish_date: "2026-05-05",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/BsHrg9OSpgQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:33",
    software_used: ["CapCut"],
  },
  {
    id: "WPpFZ5OMINQ",
    video_title: "हर रात 4 Erections | Science क्या कहती है?",
    video_description: "Insights into how morning erections function across all ages sync with REM sleep cycles without requiring sexual thoughts.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "WPpFZ5OMINQ",
    publish_date: "2026-05-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/WPpFZ5OMINQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:37",
    software_used: ["CapCut"],
  },
  {
    id: "5maln15Dfrk",
    video_title: "टेढ़ा Penis से Partner Unhappy? Doctor बोले...",
    video_description: "Addressing misconceptions regarding penile curvature, explaining that it rarely affects intimacy and debunking online pills or correction devices.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "5maln15Dfrk",
    publish_date: "2026-04-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/5maln15Dfrk",
    project_images: [],
    category: ["Shorts"],
    duration: "0:36",
    software_used: ["CapCut"],
  },
  {
    id: "977u2dwYd_0",
    video_title: "Penis पहले Straight था, अब Tedha — Serious है?",
    video_description: "Clinical clarity on whether a shift or curvature in shape over time is serious, highlighting what symptoms require medical attention.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "977u2dwYd_0",
    publish_date: "2026-04-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/977u2dwYd_0",
    project_images: [],
    category: ["Shorts"],
    duration: "0:22",
    software_used: ["CapCut"],
  },
  {
    id: "xNDfUooyCqw",
    video_title: "Peyronie's Disease क्या है? — डरो मत, समझो",
    video_description: "An explanation of Peyronie's disease, how internal plaque/scar tissue causes bending during an erection, and who it commonly affects.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "xNDfUooyCqw",
    publish_date: "2026-04-23",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/xNDfUooyCqw",
    project_images: [],
    category: ["Shorts"],
    duration: "0:38",
    software_used: ["CapCut"],
  },
  {
    id: "qZtOwEOOVKM",
    video_title: "Curved Penis से Confidence टूट रहा है? ये सुनो",
    video_description: "A look into how stressing over curvature causes performance anxiety, low confidence, and mental health strain.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "qZtOwEOOVKM",
    publish_date: "2026-04-21",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/qZtOwEOOVKM",
    project_images: [],
    category: ["Shorts"],
    duration: "0:29",
    software_used: ["CapCut"],
  },
  {
    id: "H9N5jvbmNhI",
    video_title: "Penis Size की सच्चाई — Doctor ने सब बता दिया",
    video_description: "Medical facts concerning the average erect length for Indian men, matching it closely against global metrics to clear up internet-born myths.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "H9N5jvbmNhI",
    publish_date: "2026-04-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/H9N5jvbmNhI",
    project_images: [],
    category: ["Shorts"],
    duration: "0:39",
    software_used: ["CapCut"],
  },
  {
    id: "eUR0CIZ2ow0",
    video_title: "Size छोटा लग रहा है? असली Problem ये हो सकती है",
    video_description: "Explaining a massive study revealing that anxiety about size often misidentifies an underlying issue with erection firmness or quality.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "eUR0CIZ2ow0",
    publish_date: "2026-04-03",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/eUR0CIZ2ow0",
    project_images: [],
    category: ["Shorts"],
    duration: "0:43",
    software_used: ["CapCut"],
  },
  {
    id: "CRxEa40onZ8",
    video_title: "Size छोटा है? Doctor बोले — पहले ये Check करो",
    video_description: "Breaking down \"small penis anxiety\" and explaining how weight gain and grooming directly alter visual perception.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "CRxEa40onZ8",
    publish_date: "2026-04-04",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/CRxEa40onZ8",
    project_images: [],
    category: ["Shorts"],
    duration: "0:57",
    software_used: ["CapCut"],
  },
  {
    id: "KIi-GNrS3Wo",
    video_title: "Indian मर्दों का Size छोटा होता है?",
    video_description: "Deep-diving into decades of medical data analyzing why perceptions around the physical attributes of Indian men are flawed.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "KIi-GNrS3Wo",
    publish_date: "2026-04-04",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/KIi-GNrS3Wo",
    project_images: [],
    category: ["Shorts"],
    duration: "0:35",
    software_used: ["CapCut"],
  },
  {
    id: "R9QeTSN-nO8",
    video_title: "Oil से Size बढ़ेगा? Doctor का सीधा जवाब",
    video_description: "Differentiating medical reality from promotional claims, explaining that creams or oils only briefly increase surface blood flow but cannot expand physical tissue.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "R9QeTSN-nO8",
    publish_date: "2026-04-05",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/R9QeTSN-nO8",
    project_images: [],
    category: ["Shorts"],
    duration: "0:46",
    software_used: ["CapCut"],
  },
  {
    id: "9FybW5O9YlY",
    video_title: "Normal Penis Size कितना है? 100 में से 90 मर्द...",
    video_description: "Presenting the anatomical bell curve showing where the vast majority of men place regarding measurement metrics.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "9FybW5O9YlY",
    publish_date: "2026-04-05",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/9FybW5O9YlY",
    project_images: [],
    category: ["Shorts"],
    duration: "0:39",
    software_used: ["CapCut"],
  },
  {
    id: "fgqYbtZpkBY",
    video_title: "Size बढ़ाने वाले Products? सब SCAM है — Doctor Explains",
    video_description: "Exposing tissue expansion product scams and directing focus toward treating actual erectile dysfunction effectively.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "fgqYbtZpkBY",
    publish_date: "2026-04-06",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/fgqYbtZpkBY",
    project_images: [],
    category: ["Shorts"],
    duration: "0:43",
    software_used: ["CapCut"],
  },
  {
    id: "G5qRYKkRnWQ",
    video_title: "Bigger Penis Is Better? सच जानें",
    video_description: "Explaining anatomical sensitivity facts regarding female pleasure zones and detailing the nerve endings responsible for stimulation.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "G5qRYKkRnWQ",
    publish_date: "2026-04-07",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/G5qRYKkRnWQ",
    project_images: [],
    category: ["Shorts"],
    duration: "0:51",
    software_used: ["CapCut"],
  },
  {
    id: "mdbenYuF7pM",
    video_title: "Indian Men का Average Size — Doctor-Measured Data",
    video_description: "Real clinical experiences breaking down how patients confuse performance/erection quality anxiety with sizing issues.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "mdbenYuF7pM",
    publish_date: "2026-04-08",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/mdbenYuF7pM",
    project_images: [],
    category: ["Shorts"],
    duration: "0:41",
    software_used: ["CapCut"],
  },
  {
    id: "oMBUNwPHD-w",
    video_title: "Porn vs Reality — Penis Size का सच क्या है?",
    video_description: "Dissecting how curated camera angles, lighting, and selective casting set up deeply unrealistic and harmful standard expectations.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "oMBUNwPHD-w",
    publish_date: "2026-04-09",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/oMBUNwPHD-w",
    project_images: [],
    category: ["Shorts"],
    duration: "0:45",
    software_used: ["CapCut"],
  },
  {
    id: "UMzqMhH6vQI",
    video_title: "Straight Penis कितने मर्दों का होता है? जवाब चौंकाएगा",
    video_description: "Explaining that curvatures up to 30 or 60 degrees can be completely natural and stable, without impacting physical capability.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "UMzqMhH6vQI",
    publish_date: "2026-04-18",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/UMzqMhH6vQI",
    project_images: [],
    category: ["Shorts"],
    duration: "0:28",
    software_used: ["CapCut"],
  },
  {
    id: "EwpM2r4MLWk",
    video_title: "Penis टेढ़ा दिखता है? 56% मर्द ग़लत समझते हैं",
    video_description: "Discussing how looking downward creates an unflattering perspective angle, causing more than half of men to overestimate asymmetry.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "EwpM2r4MLWk",
    publish_date: "2026-04-19",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/EwpM2r4MLWk",
    project_images: [],
    category: ["Shorts"],
    duration: "0:28",
    software_used: ["CapCut"],
  },
  {
    id: "v3tMii54Pqk",
    video_title: "Masturbation से Penis टेढ़ा होता है? सच जान लो",
    video_description: "Debunking a common physiological myth by explaining that normal habits do not cause curvature or structural alignment shifts.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "v3tMii54Pqk",
    publish_date: "2026-04-20",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/v3tMii54Pqk",
    project_images: [],
    category: ["Shorts"],
    duration: "0:35",
    software_used: ["CapCut"],
  },
  {
    id: "2sZcM85ENE8",
    video_title: "Penis टेढ़ा — कब Normal, कब Doctor ज़रूरी?",
    video_description: "A definitive guide outlining the baseline differences between natural long-term curvature and sudden shifts that demand professional care.",
    tags: ["MorningErections", "MensHealth", "HardFacts", "Shorts"],
    cover_image: "2sZcM85ENE8",
    publish_date: "2026-04-20",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/2sZcM85ENE8",
    project_images: [],
    category: ["Shorts"],
    duration: "0:50",
    software_used: ["CapCut"],
  },
  {
    id: "placeholder-meta-ad-id",
    video_title: "Upcoming Meta Ad Project Title",
    video_description: "Description structure ready for your upcoming Meta Ad video metrics and copy details.",
    tags: ["MetaAds", "PaidMedia", "Marketing"],
    cover_image: "placeholder-meta-ad-image",
    publish_date: "2026-06-25",
    client_name: "RaazMD",
    client_image: "/companies/RaazMD.png",
    client_feedback: "",
    video_link: "https://facebook.com/ads/library",
    project_images: [],
    category: ["Meta Ads"],
    duration: "0:00",
    software_used: ["CapCut"],
  },
];
